jobs:
- job: Bundle
  pool:
    vmImage: 'macOS-10.15' # TODO: Make this a parameter
  steps:
  - script: echo "Publishing ${{ variables.version }}"
    displayName: Set Version
  - script: npm install
    displayName: NPM Install
  - script: npm shrinkwrap
    displayName: NPM Shrinkwrap
  - script: echo "PLACEHOLDER"
    displayName: Smoke Tests
  - script: echo "PLACEHOLDER"
    displayName: Git Tag